apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  labels:
    name: hello-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: hello-app
  template:
    metadata:
      labels:
        name: hello-app
    spec:
      imagePullSecrets:
        - name: artifactory-clm-sl
      containers:
      - name: hello-app
        image: <image-name>
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 5000
          - name: metrics
            containerPort: 8000
        resources:
          limits:
            cpu: "100m"
          requests:
            cpu: "100m"