apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-app
  # autoscale between 1 and 10 replicas
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20
